### ISSUE TITLE
[Feature request] Listen for events in a pre-existing voice channel

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [discord/gamesdk-and-dispatch#124]
From what I've read and attempted, there doesn't seem to be a way to make the SDK use pre-existing voice channels, it seemingly has to generate it's own lobby. A way to specify that the SDK should connect to a voice channel instead of the normal lobby would be appreciated.

(I've already tried the discord dev server, nobody seems to know)

**Comment by Jump-Suit** [comment]
Refer to this statement I very recently made in Discord Devs: https://discord.com/channels/613425648685547541/613425918748131338/864257990333038593
GameSDK does NOT support interacting with Discord Server Voice Channels, if that is what you mean by "pre-existing channels". 
Lobbies are focused on their own subset voice channels. As such, you CAN have a lobby voice chat, AND be in a server voice chat *at the same time*.

**Comment by ASpoonPlaysGames** [comment]
Thanks for the info, shame that the functionality from the RPC wasn't carried over

**Comment by Jump-Suit** [comment]
RPC prior didn't have this functionality for lobbies even so, only just rich presence afaik. 
The RPC API (https://discord.com/developers/docs/topics/rpc) is a different entire protocol than GameSDK's RPC (https://github.com/discord/discord-rpc) predecessor mind you.

**Comment by ASpoonPlaysGames** [comment]
The RPC had the ability to join voice channels, and respond to events such as users joining and leaving voice channels, and (what I'm trying to do) start/stop speaking events. The GameSDK seems to have similar events for speaking, but doesn't support interacting with discord server voice channels as you said earlier

**Comment by Jump-Suit** [comment]
I don't recall the previous iteration having such functionality. Then again, I never looked into discord-rpc. Since its deprecated.
My github issue with the Overlay Widget will enlighten you abit about what the Lobby Voice Chat looks like: https://github.com/discord/gamesdk-and-dispatch/issues/55 

![](https://user-images.githubusercontent.com/26616362/91241068-6432e380-e709-11ea-9fe7-5f9a7683346f.png)
Referenced from my github issue linked above.
