### ISSUE TITLE
[Question] [GameSDK] Which is the "latest" version?

### ISSUE THREAD

**Issue by JnCrMx** [discord/gamesdk-and-dispatch#132]
I am confused about the versioning, because
- https://dl-game-sdk.discordapp.net/latest/discord_game_sdk.zip is version ``3.0.1``
- https://discord.com/developers/docs/game-sdk/sdk-starter-guide links to version ``2.5.6``
- the latest version I was able to find is version ``3.2.0``

Which of these versions should be used or are all of them considered usable?
Overall this confusion emphasises the request #125 as having a more comprehensive version list could be very helpful for chosing the right version.

**Comment by vkuhlmann** [comment]
Indeed a confusing topic. Some months ago, there was a little discussion on this on the Discord Developers server (http://discord.gg/discord-developers) starting at this message: https://canary.discord.com/channels/613425648685547541/613425918748131338/818861763968761866

Main takeaways:
* _3.0.1 (latest)_
  About the docs not pointing to `/latest`:
  > He stated he wasn't going to redirect to latest due to breaking changes being introduced.

  > I would reflect it as latest as a tag, but not stable.

* _3.1.0_
  > atm 3.1.0 is still untested much, which is why Mason hasn't considered it stable

* _3.2.0_
  That one isn't even announced, while 3.1.0 was. As 3.1.0 can't even be considered stable, using 3.2.0 is extra risky.

* _2.5.6_
  This version is used in the docs, and it can be regarded as the immediate predecessor of 3.1.0, in terms of announcements and/or documentation. As 3.1.0 isn't considered stable yet, 2.5.6 should be your go-to version by default.

My suggestion: use 2.5.6. I think it's what the documentation uses too. However, I've seen people say that something didn't work entirely for them in 2.5.6 and hence switched to 3.1.0, namely for IL2CPP.

Because of this jungle of versions, someone made a list of them. This was also what started the discussion linked above about the different versions:
https://discord.joezwet.dev/, https://discord.joezwet.dev/#/versions

**Comment by JnCrMx** [comment]
Thank you a lot for the explanation!
