### ISSUE TITLE
Game SDK Lobby Creation Error

### ISSUE THREAD

**Issue by BrynPrez** [discord/gamesdk-and-dispatch#134]
CreateLobby function used exactly as the example on the sdk documentation catches unknown error since the latest Discord update.

Engines where we have seen this error: Godot 3.3.2, Unity 2020.1.6f1

1.Try to create lobby
2.Gets stuck or throws error depending on the game's exception handler.

Screenshots
From Discord Developers Server (Users cut-out in case of privacy issues): 
![image](https://user-images.githubusercontent.com/60448364/129489697-457cdcd8-b5d8-4d25-aa18-c14bd6bbca35.png)
![image](https://user-images.githubusercontent.com/60448364/129489787-2bf04a21-bb95-4a38-97fc-529534cbfe6a.png)
From my own project:
![image](https://user-images.githubusercontent.com/60448364/129489860-c771bb6c-5f31-49ea-bcc1-5d08e798a03a.png)

**Comment by shadowfox87** [comment]
We also had this issue where several thousand users were unable to create discord lobby. Thus game invites and in-game chat didn't work, since a discord lobby is needed for it. We traced the issue to something Discord recently made changes to their routing so it picks the best region based on IP. This led to a region string being required to be sent for a discord lobby to be created, which the sdk doesn't send those and so it is different from what the endpoint expects.

They are working on a fix. I'm just letting you know since this affects everyone who uses the sdk.

**Comment by shadowfox87** [comment]
It's been fixed since 1 hour ago.

**Comment by BrynPrez** [comment]
Yes, we tested it on our game and I can confirm it's fixed.
