### ISSUE TITLE
dispatch error when logging in: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'.

### ISSUE THREAD

**Issue by cfanoulis** [discord/gamesdk-and-dispatch#18]
**Describe the bug**
When trying to login, dispatch burps the following error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Steps to reproduce**
1. Run `dispatch login`
2. See error

**Expected behavior**
The login flow begins

**Actual behaviour**
Dispatch panics and throws the above error

**Additional context**
Full trace: https://hasteb.in/wapizeyu.rb
I was suggested to downgrade openssl, but that didn't help

**Comment by msciotti** [comment]
This is a known issue with linux and Dispatch. Some more info:

> I looked at the backtrace that occurs on linux, and it seems like Discord uses reqwest per said libraries README OpenSSL 1.0.1, 1.0.2, or 1.1.0 is supported. So you can attempt to roll back in-order to make it work. Rolling back your openssl comes with consequences though, such as possibly completely messing up your installation.

Downgrading OpenSSL to 1.1.0 or lower should work, what did you downgrade to?

In the meantime, raising this issue internally again.

**Comment by sylveon** [comment]
Downgrading major OpenSSL versions is always a *terrible* idea because a lot of critical system components are linked to it, and pin to a major version (a program linked against 1.0 can't use 1.1 and vice-versa). This is not a good suggestion, and it will most likely lead to more broken Linux installs than fixed dispatch installs.

If you are on Arch Linux, you can install the `openssl-1.0` package to keep both major versions installed side by side: https://www.archlinux.org/packages/core/x86_64/openssl-1.0/

**Comment by cfanoulis** [comment]
heyo, any update on this?

**Comment by msciotti** [comment]
We've got a working version that we'll be releasing shortly!

**Comment by cfanoulis** [comment]
hooray! Thanks a lot!
