### ISSUE TITLE
[Feature] Allow for Pulling Achievements outside of HTTP Endpoint and into base GameSDK Functions.

### ISSUE THREAD

**Issue by Jump-Suit** [discord/gamesdk-and-dispatch#9]
So far, you can only grab Achievements from the base GameSDK (outside of the HTTP Endpoint) for the Player's Achievements? Why can't we just pull the entire list and then have a Player's Status on the given Achievements be ontop of that? As it stands right now there is no way to show a Player what all Available achievements (excluding secret ofc) so they know what Discord Achievements there are? (I am not very familiar with parsing HTTP Endpoints, I've nailed the base GameSDK coding so hence why I am requesting this!) 
Cheers!

**Comment by msciotti** [comment]
This is probably not something we'll include in the base SDK. Since the achievements are defined by you, you can certainly hard-code them into your game for reference if you don't want to pull them from our HTTP endpoint.

Otherwise, fetching from the endpoint is definitely the way to go. The SDK is intended for realtime info and updates, and the actual achievements themselves are static. User progress on those achievements are not, which is why that is in the SDK.
